#!/usr/bin/env bash

function check_okay {
    if [ $? -ne 0 ]; then
        echo
        echo "installation failed..."
        exit 1
    fi
}

function do_one {
	cd $1
	check_okay
	echo
    echo 
	echo "installing $1"
    echo
    echo
	./install
	check_okay
	cd ..
}

echo

# make the lib and include directories
mkdir -p lib
mkdir -p include

# now build the modules
do_one constants
do_one superfluid
do_one nucchem
do_one neutrino
do_one dStar_eos
do_one conductivity
do_one dStar_atm
do_one dStar_crust
do_one NScool

echo
