#!/bin/bash

function check_okay {
        if [ $? -ne 0 ]
        then
                echo
                echo "FAILED"
                echo
                exit 1
        fi
}

./tester > test_output.data 2> test_log
check_okay
tail -n1 test_output.data > tmp.txt
diff tmp.txt sample_output.data
check_okay
rm tmp.txt
