#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "FAILED"
		echo
		exit 1
	fi
}

this_module=${PWD##*/}
cd make
make
check_okay
cd ../test/make
make
check_okay
cd ..
./chk
check_okay
cd ..
