#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "FAILED"
		echo
		exit 1
	fi
}

this_module=${PWD##*/}
./fetch_data
mkdir -p ../data/conductivity/cache
cp data/condall06.dat ../data/conductivity/
check_okay
./build_and_test
check_okay
cd make
make install
check_okay
cd ..
echo "module" $this_module "passed tests and was exported"
echo "****************************************************"
