#!/bin/bash

function check_okay {
        if [ $? -ne 0 ]
        then
                echo
                echo "FAILED"
                echo
                exit 1
        fi
}

./tester > test_output.data 2>&1
check_okay
ndiff --quiet test_output.data sample_output.data
