#!/bin/bash

check_okay() {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "FAILED"
		echo
		exit 1
	fi
}

this_module=${PWD##*/}
echo "building $this_module"
cd make
make
check_okay

echo "building preprocessor"
cd ../preprocessor/make
make
check_okay
cd ..

echo "generating and installing HZ90 composition file"
./generate_HZ90
check_okay
cd ..
cp data/*.bin ../data/crust_data/

echo "testing"
cd test/make
make
check_okay
cd ..
./chk
check_okay
cd ..
