#!/bin/bash

check_okay() {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "$1 FAILED"
		echo
		exit 1
	fi
}

this_module=${PWD##*/}
# ./fetch_data
# check_okay
mkdir -p ../data/crust_data/cache
check_okay "mkdir -p ../data/crust_data/cache"
./build_and_test
check_okay "./build_and_test"

cd make
make install
check_okay "make install"
cd ..
echo "module" $this_module "passed tests and was exported"
echo "****************************************************"
