#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		echo
		pwd
		echo "FAILED"
		echo
		exit 1
	fi
}

archive=JINAcrust.txz
datafile=rp03.data
datadir=../data

cd preprocessor
cd make
make
check_okay
cd ..

if [ ! -f $datadir/$datafile ]; then
    if [ -f $datadir/$archive ]; then
        tar -xf $archive
        check_okay
    else
        echo "$datafile not found"
        exit 1
    fi
fi

./process_abuntime
check_okay
rm $datadir/$datafile
./print_abuntime
check_okay
cd ..
